name: Compile & Release

on:
    push:
        paths:
            - '**.gradle'
            - '**.properties'
            - '**/src/**'
        branches:
            - "4.9"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Upload to Bintray
              run: ./gradlew bintrayUpload curseforgePublish --stacktrace
              if: |
                  !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
              env:
                  BINTRAY_USER: shedaniel
                  BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
                  curse_api_key: ${{ secrets.CURSE_API_KEY }}
